// netlify/edge-functions/analyze.js
// Streams GPT-4o response via SSE — no timeout wall.
//
// Language design:
//   - All analysis fields (summary, keyPoints, highlights, chapters, speakers)
//     are written in the user's chosen output language — always, no exceptions.
//   - transcripts.translated = transcript in chosen output language
//   - transcripts.original   = verbatim source text (built from Whisper segments server-side,
//                              NOT regenerated by GPT — so it's always accurate)
//   - transcripts.both       = interleaved, assembled by the frontend

const JSON_HEADERS = { "Content-Type": "application/json" };
const GPT_TIMEOUT_MS = 180_000; // 3 min

export default async (request) => {
  if (request.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method Not Allowed" }), { status: 405, headers: JSON_HEADERS });
  }

  const OPENAI_KEY = Deno.env.get("OPENAI_API_KEY");
  if (!OPENAI_KEY) {
    return new Response(JSON.stringify({ error: "API key not configured." }), { status: 500, headers: JSON_HEADERS });
  }

  let transcript, segments, language, detectedLanguage;
  try {
    const body = await request.json();
    transcript = body.transcript;
    segments   = body.segments || [];
    language   = body.language || "id";
    detectedLanguage = body.detectedLanguage || null;
  } catch (e) {
    return new Response(JSON.stringify({ error: "Invalid request: " + e.message }), { status: 400, headers: JSON_HEADERS });
  }

  if (!transcript || !transcript.trim()) {
    return new Response(JSON.stringify({ error: "Transcript is empty." }), { status: 400, headers: JSON_HEADERS });
  }

  // ── Output language ──
  const outputLangLabel =
    language === "en"   ? "English" :
    language === "both" ? "Indonesian and English (write everything in BOTH Indonesian and English, separated by a slash, e.g. 'Rapat dimulai / Meeting started')" :
    "Indonesian (Bahasa Indonesia)";

  // For language=both, use Indonesian as the primary for field-level instructions
  const primaryLang =
    language === "en"   ? "English" :
    language === "both" ? "Indonesian" :
    "Indonesian (Bahasa Indonesia)";

  // ── Source language ──
  const sourceLangRaw   = (detectedLanguage || "").trim().toLowerCase();
  const sourceLang      = sourceLangRaw || "the original language";
  const sourceLangLabel = sourceLang === "the original language"
    ? "the original language"
    : sourceLang.charAt(0).toUpperCase() + sourceLang.slice(1);

  // ── Build original-language transcript from Whisper segments ──
  // We do this here instead of asking GPT, so it's always verbatim and accurate.
  const originalTranscript = segments.length > 0
    ? segments.map(s => `[${s.startFormatted}] [Speaker]: ${s.text}`).join("\n")
    : transcript;

  // ── Build timestamped segment block for GPT (input only) ──
  const segmentBlock = segments.length > 0
    ? segments.map(s => `[${s.startFormatted}] ${s.text}`).join("\n")
    : transcript;
  const cappedSegments = segmentBlock.length > 12000
    ? segmentBlock.substring(0, 12000) + "\n[... truncated ...]"
    : segmentBlock;

  // ── System prompt ──
  // GPT is only asked to produce the analysis + translated transcript.
  // The original-language transcript is assembled above from Whisper segments.
  const systemPrompt = `You are a meeting analyst and translator. Analyze this transcript and return a JSON object.

Source language: ${sourceLangLabel}
Output language: ${outputLangLabel}

LANGUAGE RULES — ABSOLUTE, NO EXCEPTIONS:
- You MUST write ALL output fields in ${outputLangLabel}.
- This applies to EVERY field without exception: summary points, subPoints, keyPoints, highlights quote, highlights context, chapter titles, chapter summaries, speaker summaries, transcript lines, everything.
- If output language is Indonesian, write in Indonesian. If English, write in English. If both, write "Indonesian / English" for each field.
- Do NOT default to English. Do NOT mix languages unless output language explicitly says "both".

CONTENT RULES — sections must be DISTINCT:
- CHAPTERS: Time blocks by topic. Title = actual topic discussed. No decisions here.
- KEY POINTS: Only explicit decisions, commitments, action items with WHO + WHAT.
- HIGHLIGHTS: 2-4 quotes that are surprising or decisive. Translate quotes to output language. Explain why each matters.
- SUMMARY: Past-tense narrative with specific names/numbers. Do NOT repeat key points verbatim.
- TRANSCRIPT (translated): Full translation of every utterance in output language. Format: "[M:SS] [Speaker Name]: text"

Speaker detection: use real names if mentioned, else Speaker A/B/C. Be consistent across all fields.
Translation: natural and contextual, never literal. Match the formality level of the original.

CRITICAL: Return ONLY valid JSON. No markdown. No code fences. No text outside the JSON.

{
  "speakers": [{"id":"speaker_a","label":"Speaker A","name":null,"role":null,"summary":"<in output language>"}],
  "chapters": [{"title":"<in output language>","timestamp":"0:00 - 2:30","summary":"<in output language>"}],
  "tabs": {
    "summary": [{"point":"<in output language>","subPoints":["<in output language>"]}],
    "keyPoints": [{"point":"<WHO> <WHAT> — in output language","subPoints":["<detail in output language>"]}],
    "highlights": [{"speaker":"Speaker A","quote":"<translated to output language>","context":"<in output language>"}]
  },
  "transcripts": {
    "translated": "[0:00] [Speaker A]: <full translation in output language>\\n[0:05] [Speaker B]: <translation>"
  }
}`;

  // ── Call GPT-4o with timeout ──
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), GPT_TIMEOUT_MS);

  let gptResponse;
  try {
    gptResponse = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${OPENAI_KEY}` },
      signal: controller.signal,
      body: JSON.stringify({
        model: "gpt-4o",
        max_tokens: 8192,
        temperature: 0.1,
        stream: true,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: `Timestamped transcript to analyze and translate:\n${cappedSegments}` },
        ],
      }),
    });
  } catch (e) {
    clearTimeout(timer);
    const msg = e.name === "AbortError"
      ? "Analysis timed out after 3 minutes. The recording may be too long."
      : "Failed to reach OpenAI: " + e.message;
    return new Response(JSON.stringify({ error: msg }), { status: 503, headers: JSON_HEADERS });
  }
  clearTimeout(timer);

  if (!gptResponse.ok) {
    const errText = await gptResponse.text();
    let errMsg = `OpenAI error (${gptResponse.status})`;
    try { errMsg = JSON.parse(errText).error?.message || errMsg; } catch {}
    return new Response(JSON.stringify({ error: errMsg }), { status: gptResponse.status, headers: JSON_HEADERS });
  }

  // ── Stream SSE back to browser ──
  const { readable, writable } = new TransformStream();
  const writer = writable.getWriter();
  const enc = new TextEncoder();

  const send = async (obj) => {
    try { await writer.write(enc.encode("data: " + JSON.stringify(obj) + "\n\n")); }
    catch (_) { /* client disconnected */ }
  };

  (async () => {
    let accumulated = "";
    let lineBuf = "";

    try {
      const reader = gptResponse.body.getReader();
      const dec = new TextDecoder();

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        lineBuf += dec.decode(value, { stream: true });

        let nl;
        while ((nl = lineBuf.indexOf("\n")) !== -1) {
          const line = lineBuf.slice(0, nl).trimEnd();
          lineBuf = lineBuf.slice(nl + 1);
          if (!line.startsWith("data: ")) continue;
          const raw = line.slice(6).trim();
          if (raw === "[DONE]") continue;
          let parsed;
          try { parsed = JSON.parse(raw); } catch { continue; }
          const token = parsed.choices?.[0]?.delta?.content;
          if (token) { accumulated += token; await send({ token }); }
        }
      }

      // Strip stray markdown fences GPT adds despite instructions
      const clean = accumulated
        .replace(/^```json\s*/m, "").replace(/^```\s*/m, "").replace(/\s*```$/m, "").trim();

      // Extract outermost JSON object defensively
      const jsonStart = clean.indexOf("{");
      const jsonEnd   = clean.lastIndexOf("}");
      const jsonStr   = jsonStart !== -1 && jsonEnd !== -1
        ? clean.slice(jsonStart, jsonEnd + 1)
        : clean;

      let result;
      try {
        result = JSON.parse(jsonStr);
      } catch (e) {
        await send({ error: "Failed to parse analysis. Try a shorter recording. Raw: " + clean.substring(0, 200) });
        return;
      }

      // ── Assemble transcript fields ──
      // translated: from GPT (in chosen output language)
      // original:   built from Whisper segments verbatim (source language, always accurate)
      // both:       send both so the frontend can interleave them
      if (!result.transcripts) result.transcripts = {};
      result.transcripts.translated = result.transcripts.translated || "";
      result.transcripts.original   = originalTranscript;  // verbatim from Whisper

      // Send originalTranscript and detectedLanguage so frontend can build "both" view
      result._meta = {
        sourceLang: sourceLangLabel,
        outputLang: language,
      };

      await send({ done: true, result });
    } catch (err) {
      await send({ error: "Stream error: " + err.message });
    } finally {
      try { await writer.close(); } catch (_) { /* already closed */ }
    }
  })();

  return new Response(readable, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      "X-Accel-Buffering": "no",
    },
  });
};
